/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.53
 * Generated at: 2021-09-30 16:32:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("/* style header navigation bar and dropdown buttons */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\r\n");
      out.write("    background-image:linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),url(web.jpg);\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: fit-content;\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("    background-position:center;\r\n");
      out.write(" \r\n");
      out.write("font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("padding: 0px 5px 0px 5px;\r\n");
      out.write("grid-template-columns: repeat(auto-fill,minmax(200px, 1fr));\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".Maintxt{\r\n");
      out.write("font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("color : #1c1f4c;\r\n");
      out.write("text-shadow: 5px 5px 7px #555151;\r\n");
      out.write("font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("h3{\r\n");
      out.write("font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*----------------------------------Who we are-------------------------------*/\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".whoWe{\r\n");
      out.write("padding-right: 35%;\r\n");
      out.write("padding-left: 5%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".whoWeAreimg{\r\n");
      out.write("float: right;\r\n");
      out.write("padding-top: 50px;\r\n");
      out.write("padding-right: 30px;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".mtitle{\r\n");
      out.write("font-size: 40px;\r\n");
      out.write("font-family:sans-serif ;\r\n");
      out.write("text-align: left;\r\n");
      out.write("}\r\n");
      out.write(".title{\r\n");
      out.write("float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("position: relative;\r\n");
      out.write("text-align: center;\r\n");
      out.write("color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".centered {\r\n");
      out.write("position: absolute;\r\n");
      out.write("top: 40%;\r\n");
      out.write("left: 89%;\r\n");
      out.write("transform: translate(-50%, -50%);\r\n");
      out.write("font-size: 50px;\r\n");
      out.write("color: white;\r\n");
      out.write("text-shadow: 2px 2px 4px #000000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button {\r\n");
      out.write("background-color: #4CAF50; /* Green */\r\n");
      out.write("border: none;\r\n");
      out.write("color: white;\r\n");
      out.write("padding: 16px 32px;\r\n");
      out.write("text-align: center;\r\n");
      out.write("text-decoration: none;\r\n");
      out.write("display: inline-block;\r\n");
      out.write("font-size: 16px;\r\n");
      out.write("margin: 4px 2px;\r\n");
      out.write("transition-duration: 0.4s;\r\n");
      out.write("cursor: pointer;\r\n");
      out.write("width: 400px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".button2 {\r\n");
      out.write("background-color: white;\r\n");
      out.write("color: black;\r\n");
      out.write("border: 2px solid #008CBA;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".button2:hover {\r\n");
      out.write("background-color: #008CBA;\r\n");
      out.write("color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".bt{\r\n");
      out.write("padding-left : 20px;\r\n");
      out.write("padding-right : 45%;\r\n");
      out.write("}\r\n");
      out.write(".bttn{\r\n");
      out.write("padding-left : 180px;\r\n");
      out.write("}\r\n");
      out.write(".text{\r\n");
      out.write("float: right;\r\n");
      out.write("padding-left: 65%;\r\n");
      out.write("padding-top: 30px;\r\n");
      out.write("color: white;\r\n");
      out.write("font-size: 20px;\r\n");
      out.write("  \r\n");
      out.write("  border: 1px solid gray;\r\n");
      out.write("  padding: 8px;\r\n");
      out.write("  text-indent: 50px;\r\n");
      out.write("  text-align: justify;\r\n");
      out.write("  letter-spacing: 3px;\r\n");
      out.write("\r\n");
      out.write("position: absolute;\r\n");
      out.write("top: 150% ;\r\n");
      out.write("left: 60%;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("h3{\r\n");
      out.write("font-size : 25px;\r\n");
      out.write("color: white;\r\n");
      out.write("font-family: Lucida Console;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("<div class = \"headphoto\">\r\n");
      out.write("<img src=\"header.jpg\" alt=\"Snow\" width=\"auto\" height=\"450px\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"centered\">Staff Management System</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"whoWeAreimg\">\r\n");
      out.write("<img src=\"pic1.png\" width=\"600px\" height=\"400px\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"text\">\r\n");
      out.write("To your business, the Staff Member management software shall be the brain and mouth of your organization.\r\n");
      out.write("Your members shall be allocated different roles and the work they perform at individual levels is interconnected to a central database, which works as the memory of your company.\r\n");
      out.write("The Staff Member management software shall use this information to help the different people make decisions within your organization.\r\n");
      out.write(" Just by a click of a button, you will know how many Staff members you are serving, how much products or services you are required to offer which member is required to do certain roles, the challenges facing your organization and ultimately, the system shall tell you how much profits you are making and your potential growth.\r\n");
      out.write("Start your free trial today by registering a free demo here. Our dedicated support team shall guide offer professional advise on the best steps to take in your journey towards attaining success.\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<h3>Staff Member</h3>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class =\"bt\">\r\n");
      out.write("<div class =\"bttn\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<a href=\"staffmemberlogin.jsp\">\r\n");
      out.write("<button class=\"button button2\">Check Staff Member Profile</button><br>\r\n");
      out.write("</a>\r\n");
      out.write("<a href=\"applyinsert.jsp\">\r\n");
      out.write("<button class=\"button button2\">Apply Leave</button><br>\r\n");
      out.write("</a>\r\n");
      out.write("<a href=\"viewleave.jsp\">\r\n");
      out.write("<button class=\"button button2\">Update Leave</button><br>\r\n");
      out.write("</a>\r\n");
      out.write("<a href=\"viewleave.jsp\">\r\n");
      out.write("<button class=\"button button2\">Delete Leave</button><br>\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<hr>\r\n");
      out.write("<br>\r\n");
      out.write("<h3>Payroll Clack</h3>\r\n");
      out.write("<div class =\"bttn\">\r\n");
      out.write("\r\n");
      out.write("<a href=\"billMenu.jsp\">\r\n");
      out.write("<button class=\"button button2\">Pay Bill</button><br>\r\n");
      out.write("</a>\r\n");
      out.write("<a href=\"GenerateSalaryForm.jsp\">\r\n");
      out.write("<button class=\"button button2\">Generate Salary</button><br>\r\n");
      out.write("</a>\r\n");
      out.write("<a href=\"viewPaySlip.jsp\">\r\n");
      out.write("<button class=\"button button2\">View Salary</button><br>\r\n");
      out.write("</a>\r\n");
      out.write("<a href=\"viewPaySlip.jsp\">\r\n");
      out.write("<button class=\"button button2\">Update Salary</button><br>\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("<hr>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h3>Department Manager</h3>\r\n");
      out.write("<div class =\"bttn\">\r\n");
      out.write("\r\n");
      out.write("<a href=\"insertSfMemForm.jsp\">\r\n");
      out.write("<button class=\"button button2\">Add New Staff Member</button><br>\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("<a href=\"ManagerViewLogin.jsp\">\r\n");
      out.write("<button class=\"button button2\">Update Staff Member Details</button><br>\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("<a href=\"ManagerViewLogin.jsp\">\r\n");
      out.write("<button class=\"button button2\">Delete Staff member</button><br>\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
